version: '3.2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '8016:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=tee
      - MONGO_INITDB_ROOT_PASSWORD=f217s18AhSd
    command: mongod --auth
    volumes:
      - /media/NewHDD/erp/mongo-data:/data/db
    networks:
      - tee
    restart: always
  proxy:
    image: "tee-id-proxy:latest"
    ports:
      - '8005:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB: 'id-proxy'
      DB_USER: 'tee'
      DB_PASS: 'f217s18AhSd'
      DB_SERVERS: 'mongodb:27017'
      SECRET_KEY: 'cur$$123$$jl1haG'
      EXPIRE_TOKEN: '100y'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      AUTHORIZATION_CMS_URL: "http://authorization:3000/authorization"
      INTERNAL_TOKEN: '123'
    networks:
      - tee
    restart: always

  upload:
    image: "tee-upload:latest"
    ports:
      - '8010:3000'
    environment:
      PORT: '3000'
      DEST_LOCATION: '/uploads'
      SECRET_KEY : 'cur$$123$$jl1haG'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      INTERNAL_TOKEN: '123'
    networks:
      - tee
    restart: always
    volumes:
      - /media/NewHDD/erp/uploadFolder:/uploads
networks:
  tee:
    driver: bridge