version: '3.2'

services:
  mongodb:
    image: mongo:latest
    ports:
      - '8010:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=teeprogram
      - MONGO_INITDB_ROOT_PASSWORD=@teeid@1234
    command: mongod
    volumes:
      - /media/NewHDD/erp/mongo-data:/data/db
    networks:
      - tee-id
    restart: always
  tee-upload:
    image: "tee-upload:latest"
    ports:
      - '8001:3000'
    environment:
      PORT: '3000'
      DEST_LOCATION: '/uploads'
      SECRET_KEY : 'cur$$123$$jl1haG'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      INTERNAL_TOKEN: '123'
    networks:
      - tee-id
    restart: always
    volumes:
      - /media/NewHDD/erp/uploadFolder:/uploads
  tee-id-proxy:
    image: "tee-id-proxy:latest"
    ports:
      - '8000:3000'
    environment:
      PORT: '3000'
      TZ: 'Asia/Bangkok'
      DB: 'tee'
      DB_USER: 'teeprogram'
      DB_PASS: '@teeid@1234'
      DB_SERVERS: 'mongodb:27017'
      SECRET_KEY: 'cur$$123$$jl1haG'
      SECRET_KEY_CMS: 'cur$$1223456ABC@!$$jl1haG'
      AUTHORIZATION_CMS_URL: "http://authorization:3000/authorization"
      INTERNAL_TOKEN: '123'
    networks:
      - tee-id
    restart: always
networks:
  tee-id:
    driver: bridge